services:
  rain-alert:
    image: ghcr.io/oneautumnmango/preemptive-rain-alert:dev
    environment:
      - OWM_API_KEY=your_key_here
      - LOCATION_LAT=1.3521
      - LOCATION_LON=103.8198
      - LOCATION_NAME=Singapore
      - APPRISE_URLS=discord://webhook_id/webhook_token
    restart: unless-stopped
